--INSERT INTO DeclaracionJurada (IdDeclaracion) VALUES (1)
--UPDATE DeclaracionJurada SET IdDeclaracion = 1 WHERE IdDeclaracion = 2
--DELETE FROM DeclaracionJurada WHERE IdDeclaracion = 1
--SELECT * FROM DeclaracionJurada